name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  check-tag:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - run: |
          git branch -r --contains $GITHUB_SHA
          mvn -B dependency:resolve
          mvn -B validate
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout=true)
          if [[ "v${POM_VERSION}" != "$VERSION" ]]; then
            echo "version mismatched. pom version=v${POM_VERSION}, tag=$VERSION"
          fi



